"""Best-of-N tournament engine (Stage 8 hypotheses / Stage 9 design).

Adds *breadth* of exploration to the otherwise single-line pipeline: instead of
generating one artifact and committing to it, generate N diverse candidates,
have an independent judge score + rank them, and keep only the single winner.

This is the complement of ``debate.py``:

  * debate    = depth  — multiple models argue distinct roles, then a judge
                synthesizes *one* output from the cross-talk.
  * tournament = breadth — N independent candidates compete, a judge scores and
                ranks them, and the *best* one wins.

Opt-in: callers route here only when ``llm.tournament_enabled`` is set and
``llm.tournament_candidates >= 2``. The pipeline stays linear — each stage still
emits a single canonical artifact (``hypotheses.md`` / ``exp_plan.yaml``); the
tournament just chooses which candidate becomes that artifact.

The engine is provider-agnostic and offline-testable: it only calls
``client.chat(messages, *, system=...)`` on whatever clients it is handed.
"""

from __future__ import annotations

import json
import logging
import os
import re
from pathlib import Path
from typing import Any

logger = logging.getLogger(__name__)


def _model_name(client: Any) -> str:
    return getattr(getattr(client, "config", None), "primary_model", "") or "unknown"


def effective_candidates(config_n: int) -> int:
    """Effective candidate count, honoring the ARC_TOURNAMENT_CANDIDATES override.

    Callers use this to decide how many candidate prompts to build.
    """
    env = os.environ.get("ARC_TOURNAMENT_CANDIDATES", "").strip()
    if env:
        try:
            return max(1, int(env))
        except ValueError:
            pass
    return max(1, int(config_n))


def _parse_winner(text: str, n_alive: int) -> tuple[int | None, dict[int, Any]]:
    """Parse the judge's JSON verdict tolerantly.

    Returns ``(winner_index, scores)``. ``winner_index`` is None when the JSON
    cannot be parsed or the winner is out of range (caller falls back to 0).
    """
    if not text:
        return None, {}
    # Strip ``` fences and grab the first {...} block.
    cleaned = re.sub(r"```(?:json)?", "", text)
    match = re.search(r"\{.*\}", cleaned, re.DOTALL)
    blob = match.group(0) if match else cleaned
    try:
        data = json.loads(blob)
    except (json.JSONDecodeError, ValueError):
        return None, {}
    scores: dict[int, Any] = {}
    for row in data.get("rankings", []) or []:
        try:
            scores[int(row["id"])] = row.get("score")
        except (KeyError, TypeError, ValueError):
            continue
    winner = data.get("winner")
    try:
        widx = int(winner)
    except (TypeError, ValueError):
        widx = None
    if widx is None or widx < 0 or widx >= n_alive:
        # Fall back to the highest-scored candidate if winner field is unusable.
        if scores:
            widx = max(scores, key=lambda k: (scores[k] is not None, scores[k]))
            if widx < 0 or widx >= n_alive:
                widx = None
        else:
            widx = None
    return widx, scores


def run_tournament(
    generators: list,
    judge: Any,
    candidate_prompts: list[tuple[str, str]],
    *,
    rank_prompt: str,
    out_dir: Path,
    prompts: Any,
    author_model: str = "",
    label: str = "candidate",
    gen_max_tokens: int = 8192,
) -> tuple[str, dict]:
    """Generate N candidates, judge-rank them, return the winning text.

    Args:
        generators: LLM clients; candidate ``i`` is generated by
            ``generators[i % len(generators)]``. Must be non-empty.
        judge: independent judge client (scores + picks winner). Falls back to
            ``generators[0]`` if None.
        candidate_prompts: ``[(system, user), ...]`` already rendered — one entry
            per candidate. Must be non-empty.
        rank_prompt: name of the judge ranking sub-prompt (``"tournament_rank"``).
        out_dir: directory for per-candidate transcripts + record.
        prompts: PromptManager (for ``sub_prompt`` rendering).
        author_model: generator model name, for provenance.
        label: filename prefix for per-candidate transcripts.

    Returns:
        ``(winner_text, record_dict)``. ``record_dict`` is also written to
        ``out_dir/tournament_record.json``.
    """
    if not generators:
        raise ValueError("run_tournament requires at least one generator")
    if not candidate_prompts:
        raise ValueError("run_tournament requires a non-empty candidate_prompts")

    out_dir.mkdir(parents=True, exist_ok=True)

    # Ablation hook (mirrors debate): collapse to a single candidate.
    if os.environ.get("ARC_ABL_DISABLE_TOURNAMENT", "").strip() == "1":
        candidate_prompts = candidate_prompts[:1]
        logger.info("ARC_ABL_DISABLE_TOURNAMENT=1 — tournament collapsed to 1 candidate")

    # --- Generate candidates ---
    # Only non-empty generations become real candidates. An empty/blank response
    # (e.g. a provider returning "" without raising — observed with some
    # OpenRouter models) must NOT count as a candidate: otherwise it inflates
    # candidates_succeeded, gets fed to the judge (which can hallucinate a score
    # for non-existent content), and could even "win" — shipping an empty
    # artifact downstream. Compacted indices keep judge_verdict "Candidate K"
    # aligned with the {label}_K.md transcript.
    candidates: list[str] = []
    cand_models: list[str] = []
    for i, (system, user) in enumerate(candidate_prompts):
        gen = generators[i % len(generators)]
        model = _model_name(gen)
        try:
            # Generous budget: reasoning models (e.g. gemini-2.5-pro) spend part
            # of max_tokens on hidden reasoning tokens that share the budget with
            # the visible output — at the 4096 default, long prompts can starve
            # the answer to empty/truncated. See gen_max_tokens.
            resp = gen.chat(
                [{"role": "user", "content": user}],
                system=system,
                max_tokens=gen_max_tokens,
            )
            text = resp.content or ""
        except Exception as exc:  # noqa: BLE001
            logger.warning("Tournament candidate (attempt %d, model=%s) failed: %s", i, model, exc)
            continue
        if not text.strip():
            logger.warning(
                "Tournament candidate (attempt %d, model=%s) returned empty output — dropped",
                i, model,
            )
            continue
        kept = len(candidates)
        candidates.append(text)
        cand_models.append(model)
        (out_dir / f"{label}_{kept}.md").write_text(text, encoding="utf-8")
        logger.info(
            "Tournament candidate=%d model=%s (%d chars)", kept, model, len(text),
        )

    if not candidates:
        raise RuntimeError("tournament produced no candidates")

    # Single survivor: no judging needed.
    if len(candidates) == 1:
        record = {
            "n": 1,
            "generator_models": cand_models,
            "winner": 0,
            "scores": {},
            "judge_model": "",
            "independent_judge": False,
            "author_model": author_model,
            "candidates_succeeded": 1,
        }
        (out_dir / "tournament_record.json").write_text(
            json.dumps(record, indent=2), encoding="utf-8"
        )
        return candidates[0], record

    # --- Judge: score + rank + pick winner ---
    judge_client = judge or generators[0]
    judge_model = _model_name(judge_client)
    combined = "\n\n---\n\n".join(
        f"### Candidate {i}\n{text}" for i, text in enumerate(candidates)
    )
    sp = prompts.sub_prompt(rank_prompt, n=len(candidates), candidates=combined)
    judge_system = (
        "You are an INDEPENDENT evaluator, distinct from the authors.\n\n"
    ) + sp.system
    winner_idx: int | None = None
    scores: dict[int, Any] = {}
    try:
        kwargs: dict[str, Any] = {"system": judge_system}
        if getattr(sp, "max_tokens", None):
            kwargs["max_tokens"] = sp.max_tokens
        resp = judge_client.chat([{"role": "user", "content": sp.user}], **kwargs)
        (out_dir / "judge_verdict.md").write_text(resp.content, encoding="utf-8")
        winner_idx, scores = _parse_winner(resp.content, len(candidates))
    except Exception as exc:  # noqa: BLE001
        logger.warning("Tournament judge failed: %s — defaulting to candidate 0", exc)

    if winner_idx is None:
        logger.warning("Tournament: unusable judge verdict — defaulting to candidate 0")
        winner_idx = 0

    record = {
        "n": len(candidate_prompts),
        "generator_models": cand_models,
        "winner": winner_idx,
        "scores": {str(k): v for k, v in scores.items()},
        "judge_model": judge_model,
        "independent_judge": bool(judge_model and judge_model != author_model),
        "author_model": author_model,
        "candidates_succeeded": len(candidates),
    }
    (out_dir / "tournament_record.json").write_text(
        json.dumps(record, indent=2), encoding="utf-8"
    )
    logger.info(
        "Tournament winner=candidate %d (judge=%s, %d candidates)",
        winner_idx, judge_model, len(candidates),
    )
    return candidates[winner_idx], record
